[package]
name = "bitcoin-rpc-json"
version = "0.19.0"
edition = "2024"

[dependencies]
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
bitcoin = { workspace = true, features = ["serde", "rand"] }
